object_type: global_settings
overrides:
  "xmla.auth.token.enabled": true
  "aggregate.snowflake.table.names.uppercase": true
  "query.drillthrough.max_rows": 1000
  "auth.xmla.kerberos.enabled": true
  "auth.xmla.kerberos.keytab": /etc/keycloak/atscale.keytab
  "auth.xmla.kerberos.spn": "HTTP/ubuntu-atscale.atscaledomain.com@ATSCALEDOMAIN.COM"
  "query.result.max_rows": 2000
